spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client_id: d115fcb7994a5c6d3e52002c84100e53
            client_secret: XaocJvied3L4Jl0XuFZ5AzwJpNNcnxZu
            redirect_uri: "http://localhost:8080/login/oauth2/code/kakao"
            authorization_grant_type: authorization_code
            client_authentication_method: client_secret_post
            scope: profile_nickname
            client_name: Kakao
        provider:
          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user_info_uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id

kakao:
  client_id: d115fcb7994a5c6d3e52002c84100e53
  client_secret: XaocJvied3L4Jl0XuFZ5AzwJpNNcnxZu
  redirect_uri: "http://localhost:8080/login/oauth2/code/kakao"